name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Install lefthook
        run: npm install -g @evilmartians/lefthook
      - name: Check Formatting (Lefthook)
        run: lefthook run pre-commit
      - name: Run tests
        run: cargo test
